services:
  page-mark-service:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    container_name: page_mark_app
    ports:
      - "3333:3333"
    env_file:
      - ./.env
    depends_on:
      - db-service
    command: [ "sh", "-c", "while ! pg_isready -h db-service -U postgres; do sleep 1; done; npm run local" ]
    networks:
      - page_mark_network

  db-service:
    image: postgres:latest
    container_name: page_mark_db
    restart: always
    environment:
      POSTGRES_USER: ${PGSQL_USER}
      POSTGRES_PASSWORD: ${PGSQL_PASSWORD}
      POSTGRES_DB: ${PGSQL_DATABASE}
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - page_mark_db_data:/var/lib/postgresql/data
    networks:
      - page_mark_network

volumes:
  page_mark_db_data:

networks:
  page_mark_network:
    driver: bridge
